### ISSUE TITLE
Providing JavaScript modules alongside the web components to work with data models and API agents

### ISSUE THREAD

**Issue by maltenorstroem** [eclipse-furo/eclipsefuro-web#2]
**Status Quo**
Furo Web relies mainly on the web component standard. Currently, it is difficult to implement pure JavaScript integration on the data models and API agents. 
 
**JavaScript modules**
It is desirable that there is an easy-to-use API for the integration of the models and API agents. This is provided as a JavaScript module.
The existing web components should also use this API.

**Business Value**
The APIs to the models and API agents enable seamless integration of any front-end technology.

**Comment by veith** [comment]
Fully implemented in furo/open-models, will be released soon
